#################
# Provider
#################

variable "profile" {
  description = "(Deprecated from version 1.1.0) The profile name as set in the shared credentials file. If not set, it will be sourced from the ALICLOUD_PROFILE environment variable."
  type        = string
  default     = ""
}

variable "shared_credentials_file" {
  description = "(Deprecated from version 1.1.0) This is the path to the shared credentials file. If this is not set and a profile is specified, $HOME/.aliyun/config.json will be used."
  type        = string
  default     = ""
}

variable "region" {
  description = "(Deprecated from version 1.1.0) The region used to launch this module resources."
  type        = string
  default     = ""
}

variable "skip_region_validation" {
  description = "(Deprecated from version 1.1.0) Skip static validation of region ID. Used by users of alternative AlibabaCloud-like APIs or users w/ access to regions that are not public (yet)."
  type        = bool
  default     = false
}
#################
# Memcache instance
#################


variable "availability_zone" {
  description = "The available zone to launch Memcache instance and other resources."
  type        = string
  default     = ""
}

variable "vswitch_id" {
  description = "The vswitch id for memcache instance."
  type        = string
  default     = ""
}

variable "security_ips" {
  description = "List of IP addresses allowed to access all memcache of an instance. The list contains up to 1,000 IP addresses, separated by commas. Supported formats include 0.0.0.0/0, 10.23.12.24 (IP), and 10.23.12.24/24 (Classless Inter-Domain Routing (CIDR) mode. /24 represents the length of the prefix in an IP address. The range of the prefix length is [1,32])."
  type        = list(string)
  default     = []
}

variable "create_instance" {
  description = "Whether to create Memcache instance. If false, you can use a existing Memcache instance by setting 'existing_instance_id'."
  type        = bool
  default     = true
}

variable "existing_instance_id" {
  description = "The Id of an existing memcache instance. If set, the 'create_instance' will be ignored."
  type        = string
  default     = ""
}

variable "instance_charge_type" {
  description = "Filter the results by charge type. Valid values: PrePaid and PostPaid. Default to PostPaid."
  type        = string
  default     = "PostPaid"
}

variable "instance_class" {
  description = "Memcache instance type. Refer the Memcache instance type reference, such as 'memcache.master.small.default', 'memcache.master.4xlarge.default', 'memcache.sharding.mid.default' etc."
  type        = string
  default     = ""
}

variable "instance_name" {
  description = "Display name of the instance, [2, 128] English or Chinese characters, must start with a letter or Chinese in size, can contain numbers, '_' or '.', '-'."
  type        = string
  default     = "tf-module-memcache"
}

variable "period" {
  description = "The duration that you will buy DB instance (in month). It is valid when instance_charge_type is PrePaid. Valid values: [1~9], 12, 24, 36. Default to 1."
  type        = number
  default     = 1
}

variable "auto_renew" {
  description = "Whether to renewal a DB instance automatically or not. It is valid when instance_charge_type is PrePaid. Default to false."
  type        = bool
  default     = false
}

variable "auto_renew_period" {
  description = "Auto-renewal period of an instance, in the unit of the month. It is valid when instance_charge_type is PrePaid. Valid value:[1~12], Default to 1."
  type        = number
  default     = 1
}

variable "private_ip" {
  description = "Set the instance's private IP."
  type        = string
  default     = ""
}

variable "instance_backup_id" {
  description = "If an instance created based on a backup set generated by another instance is valid, this parameter indicates the ID of the generated backup set."
  type        = string
  default     = ""
}

variable "tags" {
  description = "A mapping of tags to assign to the memcache instance resource."
  type        = map(string)
  default     = {}
}

variable "maintain_start_time" {
  description = "The start time of the operation and maintenance time period of the instance, in the format of HH:mmZ (UTC time)."
  type        = string
  default     = "02:00Z"
}

variable "maintain_end_time" {
  description = "The end time of the operation and maintenance time period of the instance, in the format of HH:mmZ (UTC time)."
  type        = string
  default     = "03:00Z"
}

#################
# Memcache backup_policy
#################

variable "backup_policy_backup_period" {
  description = "Memcache Instance backup policy backup period."
  type        = list(string)
  default     = []
}

variable "backup_policy_backup_time" {
  description = "Memcache instance backup policy backup time, in the format of HH:mmZ- HH:mmZ."
  type        = string
  default     = "02:00Z-03:00Z"
}

#############
# cms_alarm
#############

variable "enable_alarm_rule" {
  description = "Whether to enable alarm rule. Default to true."
  type        = bool
  default     = true
}

variable "alarm_rule_name" {
  description = "The alarm rule name."
  type        = string
  default     = ""
}

variable "alarm_rule_period" {
  description = "Index query cycle, which must be consistent with that defined for metrics. Default to 300, in seconds."
  type        = number
  default     = 300
}

variable "alarm_rule_statistics" {
  description = "Statistical method. It must be consistent with that defined for metrics. Valid values: ['Average', 'Minimum', 'Maximum']. Default to 'Average'."
  type        = string
  default     = "Average"
}

variable "alarm_rule_operator" {
  description = "Alarm comparison operator. Valid values: ['<=', '<', '>', '>=', '==', '!=']. Default to '=='."
  type        = string
  default     = "=="
}

variable "alarm_rule_threshold" {
  description = "Alarm threshold value, which must be a numeric value currently."
  type        = string
  default     = ""
}

variable "alarm_rule_triggered_count" {
  description = "Number of consecutive times it has been detected that the values exceed the threshold. Default to 3."
  type        = number
  default     = 3
}

variable "alarm_rule_contact_groups" {
  description = "List contact groups of the alarm rule, which must have been created on the console."
  type        = list(string)
  default     = []
}

variable "alarm_rule_silence_time" {
  description = "Notification silence period in the alarm state, in seconds. Valid value range: [300, 86400]. Default to 86400."
  type        = number
  default     = 86400
}

variable "alarm_rule_effective_interval" {
  description = "The interval of effecting alarm rule. It foramt as 'hh:mm-hh:mm', like '0:00-4:00'."
  type        = string
  default     = "0:00-2:00"
}